In [1]:
import numpy as np

There are three inputs, connected to one neuron, having 3 weights each input and only one bias for the output neuron

In [3]:
inputs = [3.1, 5.3, 2.1]
weights = [1.2, 2.1, 8.7]
bias = 3

output = inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias
print(output)

36.120000000000005


There are 4 inputs, connected to 3 neuron, having 4 weights for each input and 3 bias for the output neurons

In [7]:
inputs = [1, 2, 3, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
        inputs[0] * weights1[0] + inputs[1] * weights1[1] + inputs[2] * weights1[2] + inputs[3] * weights1[3] + bias1, 
         inputs[0] * weights2[0] + inputs[1] * weights2[1] + inputs[2] * weights2[2] + inputs[3] * weights2[3] + bias2,
          inputs[0] * weights3[0] + inputs[1] * weights3[1] + inputs[2] * weights3[2] + inputs[3] * weights3[3] + bias3
         ]
print(outputs)

[4.8, 1.21, 2.385]


In [5]:
inputs = [1, 2, 3, 2.5] # (4, 1) matrix

weights = [
            [0.2, 0.8, -0.5, 1.0],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]
          ]  # (3, 4) matrix
biases = [2,3,0.5]

layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)
print("Layer_Outputs: ")
print(layer_outputs)

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++

# outputs = np.dot(inputs, weights) + biases
# wont work because of shape (4, 1) * (3, 4)

outputs = np.dot(weights, inputs) + biases # (3, 4) * (4, 1)
print(outputs) # (3, 1)


Layer_Outputs: 
[4.8, 1.21, 2.385]
[4.8   1.21  2.385]


In [8]:
outputs = np.dot(np.array(inputs).T, np.array(weights).T) + biases # (1, 4) * (4, 3) 
print(outputs)

[4.8   1.21  2.385]


 ## Batch size
 Multiple inputs at once
 
 

In [22]:
inputs = [
            [1, 2, 3, 2.5],
            [2.0, 5.0, -1.0, 2.0],
            [-1.5, 2.7, 3.3, -0.8]
         ] # (3, 4) matrix

weights = [
            [0.2, 0.8, -0.5, 1.0],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]
          ]  # (3, 4) matrix

biases = [2,3,0.5]

# outputs = np.dot(inputs, weights) + biases
# wont work because of shape (3, 4) * ((3, 4).T)

outputs = np.dot(inputs, np.array(weights).T) + biases 
print(outputs) # (3, 3)

print() 
print()

import pandas as pd
import numpy as np

df = pd.DataFrame(
    outputs,
    index=["Input 1", "Input 2", "Input 3"],
    columns=["Neuron 1", "Neuron 2", "Neuron 3"]
)

print(df)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


         Neuron 1  Neuron 2  Neuron 3
Input 1      4.80     1.210     2.385
Input 2      8.90    -1.810     0.200
Input 3      1.41     1.051     0.026


## Two layers


In [26]:
weights2 = [
            [0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]
          ]  # (3, 3) matrix

biases2 = [-1, 2, -0.5]

layer1_outputs = outputs

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

df2 = pd.DataFrame(
    layer2_outputs,
    index = ["Input 1", "Input 2", "Input 3"],
    columns = ["Neuron 1", "Neuron 2", "Neuron 3"]
)

print(df2)

         Neuron 1  Neuron 2  Neuron 3
Input 1   0.50310  -1.04185  -2.03875
Input 2   0.24340  -2.73320  -5.76330
Input 3  -0.99314   1.41254  -0.35655


## Using classes to automatic the weights

In [7]:
import numpy as np
import pandas as pd

np.random.seed(0)

X1 = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]] # (4, 1) matrix

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

    def print_output(self):
        df = pd.DataFrame(
            self.output,
            index=[f"Input{i+1}" for i in range(len(self.output))],
            columns=[f"Neuron{i+1}" for i in range(self.output.shape[1])]
        )
        print(df)
        print()

layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(X1)
X2 = layer1.output
layer2.forward(X2)
X3 = layer2.output

layer1.print_output()
layer2.print_output()

         Neuron1   Neuron2   Neuron3   Neuron4   Neuron5
Input1  0.107581  1.039835  0.244624  0.318215  0.188511
Input2 -0.083498  0.708464  0.002934  0.447015  0.363605
Input3 -0.507632  0.556884  0.079878 -0.348896  0.045530

         Neuron1   Neuron2
Input1  0.148296 -0.083976
Input2  0.141003 -0.013405
Input3  0.201250 -0.072906



## Activation Functions

In [11]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()
activation2 = Activation_ReLU()

# layer1.forward(X)

#print(layer1.output)
activation1.forward(X2)
print(activation1.output)

activation2.forward(X3)
print(activation2.output)


[[0.10758131 1.03983522 0.24462411 0.31821498 0.18851053]
 [0.         0.70846411 0.00293357 0.44701525 0.36360538]
 [0.         0.55688422 0.07987797 0.         0.04553042]]
[[0.148296   0.        ]
 [0.14100315 0.        ]
 [0.20124979 0.        ]]
